---
- name: Install and configure Caddy webserver  # Любое описание
  hosts: my_servers
  become: yes
  connection: local  # аналог -c local, но для плейбуков

  roles:
    - caddy_deploy  # собственно, роль для выполнения