---
# tasks file for caddy_deploy

- name: Install prerequisites
  apt:
    pkg:
    - debian-keyring
    - debian-archive-keyring
    - curl

- name: Add key for Caddy repo
  apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    state: present
    keyring: /usr/share/keyrings/caddy-stable-archive-keyring.gpg

- name: add Caddy repo
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    state: present
    filename: caddy-stable

- name: add Caddy src repo
  apt_repository:
    repo: "deb-src [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    state: present
    filename: caddy-stable

- name: Install Caddy webserver
  apt:
    name: caddy
    update_cache: yes
    state: present

- name: Create config file
  template:
    src: templates/Caddyfile.j2  # Откуда берем
    dest: /etc/caddy/Caddyfile  # Куда кладем

- name: Create custom index.html
  copy:
    content: |
      <html>
      <head>
        <title>LR2</title>
      </head>
      <body>
        <h1>HELLO FROM WEB_HOLDERS</h1>
        <img src="rickroll.gif" alt="rickroll.gif">
      </body>
      </html>
    dest: /var/www/html/index.html

- name: Upload rickroll.gif to local server
  copy:
    src: ./templates/rickroll.gif
    dest: /var/www/html/rickroll.gif

- name: Reload with new config
  service:
    name: caddy
    state: reloaded